# -*- coding: utf-8 -*-
"""Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImjCYv4ENwDu8T5FPoMzfI0r1ES5NftH
"""

lista1 = ['Alvaro', 'Daniel', 'Pilar',  'Beatriz']

for i in lista1:
  print(i, end=' ')

print('')

t1 = (1, 'Oleg', 25.5)
l1 = ['Maria', 'Bonita']
l2 = [t1, l1]
t2 = (l2, 'manzana')

print('t1=', t1)
print('l1=', l1)
print('t2=', t2)
print('l2=', l2)

for i in t1:
  print(i)

print("\n")

for i in l1:
  print(i)

print("\n")

for i in l2:
  print(i)

print("\n")

for i in t2:
  print(i)

print(t2[0])
print(t2[1])
print("\n")

print(t2[0][0])
print(t2[0][1])
print("\n")

print(t2[0][0][0])
print(t2[0][0][1])
print(t2[0][0][2])
print("\n")

print(t2[0][1][0])
print(t2[0][1][1])
print(t2[0][0][2])
print("\n")

vocalTupla = ('a', 'e', 'i', 'o', 'u')
vocalLista = list(vocalTupla)

print(vocalTupla)
print(vocalLista)

alfabeto = 'abcdefghijklmnopqrstuvwxyz'
print("Alfabeto es un objeto string:", type(alfabeto))

alfaL = []

for i in alfabeto:
  alfaL.append(i)

print(alfaL)

N = len(alfaL)

numL = []

for i in range(N):
  numL.append(i)

print("alfaL = ", alfaL)
print("\n")
print("numL = ", numL)
print("\n")

alfanumL = alfaL + numL
alfanumLL = [alfaL, numL]

print("alfanumL = ", alfanumL)
print("\n")
print("alfanumLL = ", alfanumLL)

for i in range(N):
  print(alfanumLL[0][i], alfanumLL[1][i])

alfaL.count('c')
print(alfaL)

alfaL.remove('c')
print(alfaL)

alfaL.count('c')
print(alfaL)

alfaL.append('c')
print(alfaL)

alfaL.index('m')
print(alfaL)

alfaL.reverse()
print(alfaL)

alfaL.sort()
print(alfaL)

for i in range(N):
  print(alfanumLL[0][i], alfanumLL[1][i])

frutas = ["manzana", "kiwi", "guanabana", "limon", "nispero", "Pomelo", "Mango"]

lista2 = []

for x in frutas:
  if "a" in x:
    lista2.append(x)

print(lista2)

lista2 = [x for x in frutas if "a" in x]
print(lista2)

lista2 = [x for x in frutas if "a" not in x]
print(lista2)

lista2 = [x for x in frutas if len(x) <6]
print(lista2)

lista2 = [x for x in t1 if type(x) == int or type(x) == float]
print(lista2)

